spring:
  datasource:
    url: jdbc:postgresql://postgres-sql:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  application:
    name: docker-demo
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
